/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 5.1.1
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// Logicals struct for Logicals
type Logicals struct {
	And []AnyOfLogicalsParameter `json:"$and,omitempty"`
	Or []AnyOfLogicalsParameter `json:"$or,omitempty"`
	Not []AnyOfLogicalsParameter `json:"$not,omitempty"`
}
