/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 2.0
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// Entities struct for Entities
type Entities struct {
	// An array of extracted entities from the story body
	Body []Entity `json:"body,omitempty"`
	// An array of extracted entities from the story title
	Title []Entity `json:"title,omitempty"`
}
