/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 5.1.1
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// NestedEntity struct for NestedEntity
type NestedEntity struct {
	Id Query `json:"id,omitempty"`
	Name Query `json:"name,omitempty"`
	SurfaceFormsText Query `json:"surface_forms.text,omitempty"`
	Sentiment Query `json:"sentiment,omitempty"`
	Element Query `json:"element,omitempty"`
	LinksWikipedia Query `json:"links.wikipedia,omitempty"`
	LinksWikidata Query `json:"links.wikidata,omitempty"`
	StockTicker Query `json:"stock_ticker,omitempty"`
	Type Query `json:"type,omitempty"`
}
