/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 5.1.1
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// Parameter struct for Parameter
type Parameter struct {
	AuthorId Query `json:"author.id,omitempty"`
	AuthorName Query `json:"author.name,omitempty"`
	Body Query `json:"body,omitempty"`
	CategoriesConfident Query `json:"categories.confident,omitempty"`
	CategoriesId Query `json:"categories.id,omitempty"`
	CategoriesLevel Query `json:"categories.level,omitempty"`
	CategoriesTaxonomy Query `json:"categories.taxonomy,omitempty"`
	Clusters Query `json:"clusters,omitempty"`
	LinksPermalink Query `json:"links.permalink,omitempty"`
	EntitiesId Query `json:"entities.id,omitempty"`
	EntitiesSurfaceFormsText Query `json:"entities.surface_forms.text,omitempty"`
	EntitiesLinksWikipedia Query `json:"entities.links.wikipedia,omitempty"`
	EntitiesLinksWikidata Query `json:"entities.links.wikidata,omitempty"`
	EntitiesTitleSurfaceFormsText Query `json:"entities.title.surface_forms.text,omitempty"`
	EntitiesBodySurfaceFormsText Query `json:"entities.body.surface_forms.text,omitempty"`
	Id Query `json:"id,omitempty"`
	Language Query `json:"language,omitempty"`
	MediaImagesContentLengthMax Query `json:"media.images.content.length.max,omitempty"`
	MediaImagesContentLengthMin Query `json:"media.images.content.length.min,omitempty"`
	MediaImagesCountMax Query `json:"media.images.count.max,omitempty"`
	MediaImagesCountMin Query `json:"media.images.count.min,omitempty"`
	MediaImagesFormat Query `json:"media.images.format,omitempty"`
	MediaImagesHeightMax Query `json:"media.images.height.max,omitempty"`
	MediaImagesHeightMin Query `json:"media.images.height.min,omitempty"`
	MediaImagesWidthMax Query `json:"media.images.width.max,omitempty"`
	MediaImagesWidthMin Query `json:"media.images.width.min,omitempty"`
	MediaVideosCountMax Query `json:"media.videos.count.max,omitempty"`
	MediaVideosCountMin Query `json:"media.videos.count.min,omitempty"`
	SentimentBodyPolarity Query `json:"sentiment.body.polarity,omitempty"`
	SentimentTitlePolarity Query `json:"sentiment.title.polarity,omitempty"`
	SocialSharesCountFacebookMax Query `json:"social.shares.count.facebook.max,omitempty"`
	SocialSharesCountFacebookMin Query `json:"social.shares.count.facebook.min,omitempty"`
	SocialSharesCountRedditMax Query `json:"social.shares.count.reddit.max,omitempty"`
	SocialSharesCountRedditMin Query `json:"social.shares.count.reddit.min,omitempty"`
	SourceDomain Query `json:"source.domain,omitempty"`
	SourceId Query `json:"source.id,omitempty"`
	SourceLinksInCountMax Query `json:"source.links.in.count.max,omitempty"`
	SourceLinksInCountMin Query `json:"source.links.in.count.min,omitempty"`
	SourceLocationsCity Query `json:"source.locations.city,omitempty"`
	SourceLocationsCountry Query `json:"source.locations.country,omitempty"`
	SourceLocationsState Query `json:"source.locations.state,omitempty"`
	SourceRankingsAlexaCountry Query `json:"source.rankings.alexa.country,omitempty"`
	SourceRankingsAlexaRankMax Query `json:"source.rankings.alexa.rank.max,omitempty"`
	SourceRankingsAlexaRankMin Query `json:"source.rankings.alexa.rank.min,omitempty"`
	SourceScopesCity Query `json:"source.scopes.city,omitempty"`
	SourceScopesCountry Query `json:"source.scopes.country,omitempty"`
	SourceScopesLevel Query `json:"source.scopes.level,omitempty"`
	SourceScopesState Query `json:"source.scopes.state,omitempty"`
	StoryUrl Query `json:"story_url,omitempty"`
	StoryLanguage Query `json:"story_language,omitempty"`
	Text Query `json:"text,omitempty"`
	Title Query `json:"title,omitempty"`
	TranslationsEnBody Query `json:"translations.en.body,omitempty"`
	TranslationsEnText Query `json:"translations.en.text,omitempty"`
	TranslationsEnTitle Query `json:"translations.en.title,omitempty"`
	Entity OneOfNestedEntityLogicals `json:"entity,omitempty"`
}
